require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'DavestMoney' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-cookies', :path => '../node_modules/react-native-cookies'

  pod 'react-native-face-detection', :path => '../node_modules/react-native-face-detection'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'

  pod 'react-native-image-manipulator', :path => '../node_modules/react-native-image-manipulator'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'react-native-keyevent', :path => '../node_modules/react-native-keyevent'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'DavestMoneyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
